In [1]:
import numpy as np

# Creating numpy arrays

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
# Array Operations

In [4]:
print("Sum: ", np.sum(arr))

Sum:  15


In [5]:
print("Mean: ", np.mean(arr))

Mean:  3.0


In [6]:
print("Max: ", np.max(arr))

Max:  5


In [7]:
print("Element-wise squaring: ", arr ** 2)

Element-wise squaring:  [ 1  4  9 16 25]


# Multi-dimensional Arrays

In [8]:
matrix = np.array([[1,2,3,4],[5,6,7,8]])

In [9]:
print("Matrix: \n", matrix)

Matrix: 
 [[1 2 3 4]
 [5 6 7 8]]


In [10]:
print("Shape: ", matrix.shape)

Shape:  (2, 4)


In [11]:
print("Transpose: ", matrix.T)

Transpose:  [[1 5]
 [2 6]
 [3 7]
 [4 8]]


Create a NumPy array with numbers from 1 to 20.

In [12]:
arr_num = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

Find the mean, median, and standard deviation.

In [13]:
print("Mean: ", arr_num.mean())

Mean:  10.5


In [14]:
print("Mean: ", np.mean(arr_num))

Mean:  10.5


In [15]:
print("Median: ", np.median(arr_num))

Median:  10.5


In [16]:
print("Standard Deviation: ", np.std(arr_num))

Standard Deviation:  5.766281297335398


Create a 3x3 matrix and calculate its transpose.

In [17]:
arr_3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [18]:
print("Transpose: ", arr_3.T)

Transpose:  [[1 4 7]
 [2 5 8]
 [3 6 9]]
